# Site settings
title: Intent HQ Engineering blog
email: engineering@intenthq.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://engineering.intenthq.com" # the base hostname & protocol for your site
twitter_username: intenthq
github_username:  intenthq
permalink: /:year/:month/:title/
paginate: 5

# Build settings
markdown: kramdown
